from __future__ import annotations

import csv
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol
from urllib.parse import quote

import requests

from scripts.daily_optionInstrument_refresh import run_load_option_instruments
from src.news_analysis.reviewList.output_schema import ReviewListOutput
from src.common.config import get_settings
from src.common.models import WatchedInstrument
from src.data_manager.db.database_client import DatabaseClient


_PROJECT_ROOT = Path(__file__).resolve().parents[2]

_INDEX_TO_CSV_KEYWORDS: dict[str, list[str]] = {
    "NIFTY AUTO": ["AUTOMOBILE"],
    "NIFTY BANK": ["BANK"],
    "NIFTY CONSUMER DURABLES": ["CONSUMER DURABLE"],
    "NIFTY FINANCIAL SERVICES": ["FINANCIAL SERVICE"],
    "NIFTY FMCG": ["FAST MOVING CONSUMER", "FMCG"],
    "NIFTY HEALTHCARE INDEX": ["HEALTHCARE", "HEALTH CARE"],
    "NIFTY IT": ["INFORMATION TECHNOLOGY"],
    "NIFTY MEDIA": ["MEDIA", "ENTERTAINMENT"],
    "NIFTY METAL": ["METAL", "MINING"],
    "NIFTY OIL & GAS": ["OIL GAS", "OIL & GAS"],
    "NIFTY PHARMA": ["PHARMA"],
    "NIFTY PRIVATE BANK": ["PRIVATE BANK"],
    "NIFTY PSU BANK": ["PSU BANK"],
    "NIFTY REALTY": ["REALTY", "REAL ESTATE"],
    "NIFTY CHEMICALS": ["CHEMICAL"],
    "NIFTY CAPITAL GOODS": ["CAPITAL GOODS"],
    "NIFTY POWER": ["POWER"],
    "NIFTY TEXTILES": ["TEXTILE"],
    "NIFTY SERVICES SECTOR": ["SERVICES"],
}

_NSE_INDEX_ALIASES = {
    "AUTO": "NIFTY AUTO",
    "AUTOMOBILE": "NIFTY AUTO",
    "AUTOMOBILES": "NIFTY AUTO",
    "BANK": "NIFTY BANK",
    "BANKING": "NIFTY BANK",
    "BANKS": "NIFTY BANK",
    "CONSUMER DURABLE": "NIFTY CONSUMER DURABLES",
    "CONSUMER DURABLES": "NIFTY CONSUMER DURABLES",
    "FINANCE": "NIFTY FINANCIAL SERVICES",
    "FINANCIAL": "NIFTY FINANCIAL SERVICES",
    "FINANCIAL SERVICES": "NIFTY FINANCIAL SERVICES",
    "FMCG": "NIFTY FMCG",
    "HEALTHCARE": "NIFTY HEALTHCARE INDEX",
    "HEALTH CARE": "NIFTY HEALTHCARE INDEX",
    "IT": "NIFTY IT",
    "INFORMATION TECHNOLOGY": "NIFTY IT",
    "MEDIA": "NIFTY MEDIA",
    "METAL": "NIFTY METAL",
    "METALS": "NIFTY METAL",
    "OIL": "NIFTY OIL & GAS",
    "OIL & GAS": "NIFTY OIL & GAS",
    "OIL AND GAS": "NIFTY OIL & GAS",
    "PHARMA": "NIFTY PHARMA",
    "PHARMACEUTICAL": "NIFTY PHARMA",
    "PHARMACEUTICALS": "NIFTY PHARMA",
    "PRIVATE BANK": "NIFTY PRIVATE BANK",
    "PRIVATE BANKS": "NIFTY PRIVATE BANK",
    "PSU BANK": "NIFTY PSU BANK",
    "PSU BANKS": "NIFTY PSU BANK",
    "REAL ESTATE": "NIFTY REALTY",
    "REALTY": "NIFTY REALTY",
}


@dataclass(frozen=True)
class SectorConstituent:
    symbol: str
    name: str | None
    nse_index: str
    industry: str | None = None
    instrument_token: int | None = None
    segment: str | None = None
    tick_size: float | None = None
    lot_size: int | None = None
    is_fo_enabled: bool = False


class SectorConstituentProvider(Protocol):
    def fetch_for_sector(self, sector: str) -> list[SectorConstituent]:
        ...


@dataclass
class CsvSectorConstituentProvider:
    """
    Expands sector names by filtering stocks_universe.csv.

    The CSV is generated by the stocks-universe refresh script and carries
    Kite metadata, sector/industry data, and F&O eligibility.
    """

    csv_path: Path = field(default_factory=lambda: _PROJECT_ROOT / "stocks_universe.csv")
    fo_only: bool = True
    _rows: list[dict] = field(default_factory=list, init=False, repr=False)
    _loaded: bool = field(default=False, init=False, repr=False)

    def fetch_for_sector(self, sector: str) -> list[SectorConstituent]:
        self._ensure_loaded()
        index_name = normalize_nse_sector_index(sector)
        keywords = self._keywords_for(index_name)

        constituents: list[SectorConstituent] = []
        for row in self._rows:
            if self.fo_only and str(row.get("is_fo_enabled", "0")).strip() not in {"1", "True", "true"}:
                continue
            if row.get("instrument_type", "").strip().upper() != "STOCK":
                continue

            cell_sector = (row.get("sector") or "").upper()
            cell_industry = (row.get("industry") or "").upper()
            if any(keyword in cell_sector or keyword in cell_industry for keyword in keywords):
                constituents.append(self._to_constituent(row, index_name))

        return constituents

    def _keywords_for(self, index_name: str) -> list[str]:
        if index_name in _INDEX_TO_CSV_KEYWORDS:
            return [keyword.upper() for keyword in _INDEX_TO_CSV_KEYWORDS[index_name]]
        keyword = index_name.removeprefix("NIFTY ").strip()
        return [keyword] if keyword else [index_name]

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        if not self.csv_path.exists():
            raise FileNotFoundError(
                f"stocks_universe.csv not found at {self.csv_path}. "
                "Run scripts/daily_fetch_stocks_universe.py to generate it."
            )
        with self.csv_path.open(newline="", encoding="utf-8") as handle:
            self._rows = list(csv.DictReader(handle))
        self._loaded = True

    @staticmethod
    def _to_constituent(row: dict, nse_index: str) -> SectorConstituent:
        return SectorConstituent(
            symbol=row["tradingsymbol"].strip().upper(),
            name=row.get("name") or None,
            nse_index=nse_index,
            industry=row.get("industry") or row.get("sector") or None,
            instrument_token=_int_or_none(row.get("instrument_token")),
            segment=row.get("segment") or None,
            tick_size=_float_or_none(row.get("tick_size")),
            lot_size=_int_or_none(row.get("lot_size")),
            is_fo_enabled=str(row.get("is_fo_enabled", "0")).strip() in {"1", "True", "true"},
        )


@dataclass
class NSESectorConstituentProvider:
    """Live NSE API fallback for sector constituents."""

    timeout_seconds: int = 30
    user_agent: str = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36"
    )

    def fetch_for_sector(self, sector: str) -> list[SectorConstituent]:
        index_name = normalize_nse_sector_index(sector)
        session = requests.Session()
        headers = {
            "User-Agent": self.user_agent,
            "Accept": "application/json,text/plain,*/*",
            "Accept-Language": "en-US,en;q=0.9",
            "Referer": "https://www.nseindia.com/market-data/live-equity-market",
            "Connection": "keep-alive",
        }
        session.get("https://www.nseindia.com/", headers=headers, timeout=self.timeout_seconds)
        response = session.get(
            f"https://www.nseindia.com/api/equity-stockIndices?index={quote(index_name)}",
            headers=headers,
            timeout=self.timeout_seconds,
        )
        response.raise_for_status()
        rows = response.json().get("data") or []

        constituents: list[SectorConstituent] = []
        for row in rows:
            symbol = str(row.get("symbol") or "").strip().upper()
            if not symbol or symbol in {"NIFTY", "NIFTY50", index_name} or symbol.startswith("NIFTY "):
                continue
            meta = row.get("meta") if isinstance(row.get("meta"), dict) else {}
            constituents.append(
                SectorConstituent(
                    symbol=symbol,
                    name=row.get("companyName") or meta.get("companyName") or row.get("identifier"),
                    nse_index=index_name,
                    industry=row.get("industry") or meta.get("industry"),
                )
            )
        return constituents


@dataclass
class SectorExpansionService:
    """
    Expands reviewed sectors into stocks and inserts new stocks into WatchedInstrument.

    This service does not backfill and does not run predictions. OrchestrationService
    owns those steps so the top-level pipeline remains explicit.
    """

    constituent_provider: SectorConstituentProvider = field(default_factory=CsvSectorConstituentProvider)
    load_option_instruments_for_new_symbols: bool = True

    def expand_from_review(self, review_output: ReviewListOutput) -> dict:
        return self.expand_sectors(review_output.approved_sectors())

    def expand_sectors(self, sectors: list[str]) -> dict:
        clean_sectors = _dedupe_clean(sectors)
        if not clean_sectors:
            return {
                "triggered": False,
                "reason": "No approved sectors from reviewList.",
                "sectors": [],
                "symbols": [],
                "new_symbols": [],
            }

        sector_results: dict[str, dict] = {}
        all_constituents: dict[str, SectorConstituent] = {}
        for sector in clean_sectors:
            try:
                constituents = self.constituent_provider.fetch_for_sector(sector)
                sector_results[sector] = {
                    "nse_index": normalize_nse_sector_index(sector),
                    "constituents_found": len(constituents),
                    "symbols": [item.symbol for item in constituents],
                }
                for constituent in constituents:
                    all_constituents.setdefault(constituent.symbol, constituent)
            except Exception as exc:
                sector_results[sector] = {
                    "nse_index": normalize_nse_sector_index(sector),
                    "error": str(exc),
                    "constituents_found": 0,
                    "symbols": [],
                }

        symbols = sorted(all_constituents)
        if not symbols:
            return {
                "triggered": False,
                "reason": "No constituents resolved for the supplied sectors.",
                "sectors": clean_sectors,
                "sector_results": sector_results,
                "symbols": [],
                "new_symbols": [],
            }

        new_instruments = self._insert_new_watched_stocks(all_constituents)
        new_symbols = [instrument.tradingsymbol for instrument in new_instruments]

        option_instruments: dict | None = None
        if self.load_option_instruments_for_new_symbols and new_symbols:
            option_instruments = run_load_option_instruments(
                instrument_type="STOCK",
                underlyings=new_symbols,
            )

        return {
            "triggered": bool(new_symbols),
            "reason": None if new_symbols else "All resolved constituents are already in WatchedInstrument.",
            "sectors": clean_sectors,
            "sector_results": sector_results,
            "symbols": symbols,
            "new_symbols": new_symbols,
            "option_instruments": option_instruments,
        }

    def _insert_new_watched_stocks(
        self,
        constituents_by_symbol: dict[str, SectorConstituent],
    ) -> list[WatchedInstrument]:
        settings = get_settings()
        db = DatabaseClient(settings)
        db.connect()
        try:
            existing = db.get_watched_symbol_set(exchange="NSE", instrument_type="STOCK")
            new_symbols = sorted(set(constituents_by_symbol) - existing)
            if not new_symbols:
                return []

            needs_stockdb = [
                symbol
                for symbol in new_symbols
                if constituents_by_symbol[symbol].instrument_token is None
            ]
            stockdb_rows = (
                db.get_stock_instruments_by_symbols(needs_stockdb, exchange="NSE")
                if needs_stockdb
                else {}
            )

            watched_rows: list[WatchedInstrument] = []
            for symbol in new_symbols:
                constituent = constituents_by_symbol[symbol]
                stock = stockdb_rows.get(symbol)
                watched_rows.append(
                    WatchedInstrument(
                        tradingsymbol=symbol,
                        exchange="NSE",
                        name=constituent.name or (stock.name if stock else None),
                        instrument_token=constituent.instrument_token or (stock.instrument_token if stock else None),
                        segment=constituent.segment or (stock.segment if stock else "NSE"),
                        tick_size=constituent.tick_size or (stock.tick_size if stock else None),
                        lot_size=constituent.lot_size or (stock.lot_size if stock else 1),
                        instrument_type="STOCK",
                        sector=constituent.nse_index,
                        industry=constituent.industry or constituent.nse_index,
                        is_fo_enabled=True,
                        is_active=True,
                    )
                )

            db.upsert_watched_instruments(watched_rows)
            return watched_rows
        finally:
            db.close()


def normalize_nse_sector_index(sector: str) -> str:
    cleaned = " ".join(str(sector or "").replace("_", " ").split()).upper()
    if not cleaned:
        raise ValueError("sector must not be empty")
    if cleaned.startswith("NIFTY "):
        return cleaned
    return _NSE_INDEX_ALIASES.get(cleaned, f"NIFTY {cleaned}")


def _dedupe_clean(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        cleaned = " ".join(str(value or "").split())
        key = cleaned.upper()
        if cleaned and key not in seen:
            result.append(cleaned)
            seen.add(key)
    return result


def _int_or_none(value: str | None) -> int | None:
    try:
        return int(value) if value and value.strip() else None
    except (ValueError, TypeError):
        return None


def _float_or_none(value: str | None) -> float | None:
    try:
        return float(value) if value and value.strip() else None
    except (ValueError, TypeError):
        return None
