-- Daily NIFTY option selection generated from NiftyPrediction.
-- One row per (symbol, trade_date, model_version), where trade_date is the
-- upstream signal date. The selected option is intended for the next trading day.

CREATE TABLE IF NOT EXISTS "NiftyOptionSelection" (
    symbol                    varchar(50) NOT NULL DEFAULT 'NIFTY',
    trade_date                date        NOT NULL,
    model_version             varchar(50) NOT NULL DEFAULT 'cascade_v1',
    next_trade_date           date,
    final_prediction          varchar(20),
    prediction_direction      varchar(20),
    volatility_regime         varchar(20),
    primary_strategy          varchar(120),
    strategy_precision        double precision,
    signal_style              varchar(50),
    strength_score            double precision,
    strength_label            varchar(20),
    confidence_level          double precision,
    spot_price                double precision,
    as_of_time                timestamp,
    selected_strategy         varchar(50),
    option_bias_selected      varchar(50),
    no_trade_reason           text,
    evaluated_candidate_count integer,
    strategy_direction        varchar(20),
    entry_debit_or_credit     double precision,
    max_profit                double precision,
    max_loss                  double precision,
    breakeven                 double precision,
    reward_risk               double precision,
    selection_score           double precision,
    selection_confidence      varchar(20),
    total_delta               double precision,
    total_gamma               double precision,
    total_theta               double precision,
    total_vega                double precision,
    legs_summary              text,
    primary_buy_token         bigint,
    primary_buy_symbol        varchar(120),
    primary_buy_strike        double precision,
    primary_buy_expiry        date,
    primary_buy_option_type   varchar(10),
    primary_buy_entry_price   double precision,
    primary_buy_iv            double precision,
    primary_buy_delta         double precision,
    target_1_pct              double precision,
    target_1_price            double precision,
    target_2_pct              double precision,
    target_2_price            double precision,
    stop_loss_enabled         boolean NOT NULL DEFAULT false,
    stop_loss_pct             double precision,
    stop_loss_price           double precision,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_nifty_option_selection PRIMARY KEY (symbol, trade_date, model_version)
);

CREATE INDEX IF NOT EXISTS ix_nifty_option_selection_date
    ON "NiftyOptionSelection" (trade_date);
